### ISSUE TITLE
Source code resp. how the ping test works

### ISSUE THREAD

**Issue by XTomixxx** [nzbart/AzureSitePing#3]
Hi guys,

 i cannot find the souce code of the html page http://azureping.info/ here.
I would need the code to understand HOW the ping test work in detail: I mean, what is sent (random string, integer? how big in bytes?) how often is it sent to determine the ping to a data centre?

If you do not want to publish the code u might simply want to answer questions above. ;-)

TY!

**Comment by nzbart** [comment]
This repository is the master copy and has all the source code - in fact the site is configured for continuous deployment from this repository! 

There are certainly no secrets here - other than my passwords to Github and Azure.

There are two parts:
1. The server side (branch: master) is monitored by several Azure websites - one in each region - and automatically deployed when a change is detected.
2. The client side (branch: gh-pages) is the actual source code for a Github page.

I hope that this gives you enough information to answer any questions you have about the algorithm. Otherwise, I can try to answer specific questions here.

Note: the algorithm isn't perfect, but was the best I could do given the limitations of running within a browser. If you identify any possible improvements, please let me know.

Thanks,
Bart

**Comment by XTomixxx** [comment]
Ah, ty, the source of the client web page  is in  gh-pages, that's the trick :-)

**Comment by XTomixxx** [comment]
However, iam not a wep programming expert so maybe u can ask the following question and let save me some time.

a.) How is the ping determined; i mean what request is send to the server and what response is send back to the client?
b.) How big in size (bytes) is the request package send from client to server and what does it contain (random string, integer,...)?
c.) How big in size (bytes) is the response package send from server to client and what does it contain?
d.) How often is the request done do termine ping or is the ping computed by only 1 request (no problem, i just need to know ;-))

Ty a lot!

**Comment by nzbart** [comment]
a) The request uses JSONP (over HTTP-TCP-IP) from the browser - so it's technically not a 'ping', which uses ICMP. However, since ICMP can be treated differently from TCP through various routers, TCP will give a better idea of real-world performance because web browsing traffic is transmitted via HTTP. Most other protocols use TCP, and failing that, they all use IP (hence the name IP = Internet Protocol).

b) The request is 456 bytes on my browser. This is mostly outside my control, and is as small as I could make it.

c) The response is 501 bytes on my browser. This is mostly outside my control, and is as small as I could make it. The response body is compressed, which ironically makes it larger.

d) The request is made once to each server every time you press the GO button. You should click it a few times to make sure that you're getting consistent results.

I hope this helps.

**Comment by XTomixxx** [comment]
Thank you :-)
